name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Builder
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        install: true
        endpoint: builders

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: arm64,amd64

    - name: "Build"
      run: make build
