# This is a basic workflow that is manually triggered

name: Build Images

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "golang 1.15"
      uses: okteto/build@master
      env:
        VERSION: 1.15
      with:
        tag: okteto/golang:1
        buildargs: VERSION
        file: golang/Dockerfile
    - name: "golang 1.14"
      uses: okteto/build@master
      env:
        VERSION: 1.14
      with:
        tag: okteto/golang:1.14
        buildargs: VERSION
        file: golang/Dockerfile
